### ISSUE TITLE
bcm2835_spi_setBitOrder missing?

### ISSUE THREAD

**Issue by FreeWillaert** [gusmanb/BCM2835Managed#1]
Hi, I'm really new to SPI so I might be saying something stupid, but isn't the bcm2835_spi_setBitOrder method missing?
If not, sorry for bothering - but some explanation would be very nice.

Thanks!
Frederik

**Comment by gusmanb** [comment]
Sorry for the extreme delay!!! The notification was lost in a sea of spam, sorry.

According to the previous versions of the original library, you can read this:

    // BCM2835_SPI_BIT_ORDER_MSBFIRST is the only one suported by SPI0

And in the latest versions you can find this:

    void bcm2835_spi_setBitOrder(uint8_t order)
    {
        bcm2835_spi_bit_order = order;
    }

The thing is that "bcm2835_spi_bit_order" isn't defined anywhere, so it seems it really is not supported by the hardware.

If you have any other info feel free to reopen the issue.

Cheers!
